# Assignment 3: NumPy and Pandas Fundamentals
*Course:* GRTR 513 Decoding Python to Fuel Your Research  
*Due:* **July 24, 2026, 01:00 pm** (covers Weeks 1-6 in the [Udemy learning path](https://concordia.udemy.com/learning-paths/10727613/))  
*Estimated time:* ≈ 3–4 hours

> **Instructions:** This assignment focuses on **NumPy arrays and Pandas data structures** (Series and DataFrames).  
> You will load, explore, and manipulate your dataset using these powerful libraries.  
> Work **individually** and use **Python with NumPy and Pandas** (no visualization yet).

**Fill this in!** (You can double-click any notebook cell to edit)

---

**Student Name:** Tanzir Bin Razzaque  
**Chosen Dataset:** goodreads_books.csv  
**Dataset Source (URL or filename):** https://moodle.concordia.ca/moodle/pluginfile.php/7929315/mod_folder/content/0/goodreads_books.csv?forcedownload=1

---

## Learning Objectives
- Import and use **external libraries** (NumPy, Pandas) to extend Python's capabilities.
- Load structured data using **pd.read_csv()** and explore DataFrame properties.
- Create and manipulate **NumPy arrays** for efficient numerical computation.
- Work with **Pandas Series** to analyze individual columns.
- Perform **DataFrame operations**: filtering, indexing, and aggregation.
- Understand the relationship between NumPy arrays and Pandas data structures.

### What's Allowed / Not Allowed (for A3)
- Allowed: All basic Python, NumPy, Pandas, functions, data structures from A1-A2.
- Not allowed **for A3**: Matplotlib, Seaborn, or other visualization libraries.
- Tip: Focus on **understanding data types** (`ndarray` vs Series vs DataFrame) and when to use each!

In [1]:
# Setup and Imports
import numpy as np
import pandas as pd

In [2]:

# TODO: Set the path to your dataset file
DATA_PATH = "./data/goodreads_books.csv"

# TODO: Specify column names you'll analyze (check your dataset!)
# These should be actual column names from your CSV file
COL_NUMERIC_1 = "average_rating"        # Change me! (e.g., year, age, price)
COL_NUMERIC_2 = "ratings_count"       # Change me! (e.g., sales, temperature, count)
COL_CATEGORICAL = "title"  # Change me! (e.g., region, type, status)

# Optional: Set these if your CSV has special properties
DELIMITER = ","        # Change if not comma-separated
ENCODING = "utf-8"     # Change if needed (e.g., 'latin-1', 'iso-8859-1')

print("Setup complete!")
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

Setup complete!
NumPy version: 2.5.1
Pandas version: 3.0.3

## Task 1: Load and Explore Data with Pandas

### Part A: Load the Dataset
Use **pd.read_csv()** to load your dataset into a DataFrame. Handle the following:
1. Set the correct separator/delimiter if not comma-separated
2. Specify if there's no header row (`header=None`)
3. Handle any encoding issues

**After loading:**
- Display the first 10 rows
- Display the last 5 rows
- Print the DataFrame's shape (rows, columns)

### Part B: Explore DataFrame Properties
Using Pandas functions and methods, print the following information about your DataFrame:
1. Column names
2. Data types of each column
3. Basic statistical summary (hint: no need to perform any calculations by hand here; there is a Pandas DataFrame method that provides such a summary out of the box!)
4. Information about the DataFrame (hint: no need to perform any calculations by hand here; there is a Pandas DataFrame method that provides such *info* out of the box!)
5. Number of missing values per column (hint: use a combination of `isnull()` and `.sum()`)

In [3]:
# Task 1A: Load the dataset
df = pd.read_csv(DATA_PATH, delimiter=DELIMITER, encoding=ENCODING, on_bad_lines="skip")

# Display first and last rows
from IPython.display import display
display(df.head())
display(df.tail())
# Print shape
df.shape

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
11118,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,9781560254416,eng,512,156,20,12/21/2004,Da Capo Press
11119,45633,You Bright and Risen Angels,William T. Vollmann,4.08,0140110879,9780140110876,eng,635,783,56,12/1/1988,Penguin Books
11120,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,0140131965,9780140131963,eng,415,820,95,8/1/1993,Penguin Books
11121,45639,Poor People,William T. Vollmann,3.72,0060878827,9780060878825,eng,434,769,139,2/27/2007,Ecco
11122,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,9788497646987,spa,272,113,12,5/28/2006,Edimat Libros

(11123, 12)

In [4]:
# Task 1B: Explore properties

# Print column names
# YOUR CODE HERE
display(df.columns)
# Print data types
# YOUR CODE HERE
display(df.dtypes)
# Print statistical summary
# YOUR CODE HERE
display(df.describe())
# Print DataFrame info
# YOUR CODE HERE
display(df.info())
# Print missing values count
# YOUR CODE HERE
display(df.isna().sum())

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='str')

bookID                  int64
title                     str
authors                   str
average_rating        float64
isbn                      str
isbn13                  int64
language_code             str
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date          str
publisher                 str
dtype: object

,bookID,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,11123.000000,11123.000000,1.112300e+04,11123.000000,1.112300e+04,11123.000000
mean,21310.856963,3.934075,9.759880e+12,336.405556,1.794285e+04,542.048099
std,13094.727252,0.350485,4.429758e+11,241.152626,1.124992e+05,2576.619589
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10277.500000,3.770000,9.780345e+12,192.000000,1.040000e+02,9.000000
50%,20287.000000,3.960000,9.780582e+12,299.000000,7.450000e+02,47.000000
75%,32104.500000,4.140000,9.780872e+12,416.000000,5.000500e+03,238.000000
max,45641.000000,5.000000,9.790008e+12,6576.000000,4.597666e+06,94265.000000

<class 'pandas.DataFrame'>
RangeIndex: 11123 entries, 0 to 11122
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11123 non-null  int64
 1   title               11123 non-null  str
 2   authors             11123 non-null  str
 3   average_rating      11123 non-null  float64
 4   isbn                11123 non-null  str
 5   isbn13              11123 non-null  int64
 6   language_code       11123 non-null  str
 7     num_pages         11123 non-null  int64
 8   ratings_count       11123 non-null  int64
 9   text_reviews_count  11123 non-null  int64
 10  publication_date    11123 non-null  str
 11  publisher           11123 non-null  str
dtypes: float64(1), int64(5), str(6)
memory usage: 1.0 MB

None

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

## Task 2: NumPy Array Operations

### Part A: Convert Columns to NumPy Arrays
Select 2-3 numeric columns from your DataFrame (created in Task 1) and convert them to **NumPy arrays** using `.to_numpy()`.

For each array, use NumPy functions or methods to:
1. Print its shape
2. Print its data type
3. Print the first 10 values

### Part B: Perform Array Calculations
Using your NumPy arrays, calculate:
1. **Mean**
2. **Standard deviation**
3. **Min and max**
4. **Sum**

> **Heads-up #1 (missing values):** If your column contains missing values (NaN), plain NumPy functions like `np.mean()` will return `nan`. Either drop the missing values before converting (`df[col].dropna().to_numpy()`) or use the NaN-aware functions (`np.nanmean()`, `np.nanstd()`, etc.). This is different from Pandas, which skips NaN automatically!
>
> **Heads-up #2 (standard deviation):** Don't worry if your NumPy standard deviation differs slightly from the one shown by `describe()` in Task 1. NumPy's `std()` divides by *n* (population std) by default, while Pandas divides by *n - 1* (sample std). Both are correct, they just use different conventions.

### Part C: Array Operations
Perform at least TWO of the following operations on your arrays:
- Element-wise arithmetic (e.g., multiply array by 2, add arrays together)
- Boolean indexing (e.g., find all values greater than some threshold)
- Array comparison (e.g., compare two arrays element-wise)
- Create a new array from calculations (e.g., percentage change, ratios)

Print the results!

In [5]:
# Task 2A: Convert to NumPy arrays

# YOUR CODE HERE
arr1 = df[COL_NUMERIC_1].to_numpy()
arr2 = df[COL_NUMERIC_2].to_numpy()

# Print shape, dtype, and first 10 values for each array
# YOUR CODE HERE
print(arr1.shape)
print(arr1.dtype)
print(arr1[:10])

print(arr2.shape)
print(arr2.dtype)
print(arr2[:10])

(11123,)
float64
[4.57 4.49 4.42 4.56 4.78 3.74 4.73 4.38 4.38 4.22]
(11123,)
int64
[2095690 2153167    6333 2339585   41428      19   28242    3628  249558
    4930]

In [6]:
# Task 2B: Calculate statistics

# YOUR CODE HERE
# Calculate mean, std, min, max, sum for your arrays
print(f"arr1 mean: {arr1.mean()}, std: {arr1.std()}, min: {arr1.min()}, max: {arr1.max()}, sum: {arr1.sum()}")
print(f"arr2 mean: {arr2.mean()}, std: {arr2.std()}, min: {arr2.min()}, max: {arr2.max()}, sum: {arr2.sum()}")

arr1 mean: 3.9340753393868564, std: 0.35046955631596, min: 0.0, max: 5.0, sum: 43758.72
arr2 mean: 17942.848062573048, std: 112494.09630634527, min: 0, max: 4597666, sum: 199578299

In [7]:
# Task 2C: Array operations

# Operation 1: (describe what you're doing)
# multiply the arrays by 2 and add the arrays 
# YOUR CODE HERE
print(arr1 * 1000 + arr2)
# Operation 2: (describe what you're doing)
# ratio of the fisrt 10 values of arr1 and arr2
# YOUR CODE HERE
print(arr1[:10]/arr2[:10])
# Operation 3
# checking if the first 10 values of arr1 is > 4
print(arr1[:10] > 4)

[2100260. 2157657.   10753. ...    4780.    4489.    4023.]
[2.18066603e-06 2.08530040e-06 6.97931470e-04 1.94906362e-06
 1.15380902e-04 1.96842105e-01 1.67481057e-04 1.20727674e-03
 1.75510302e-05 8.55983773e-04]
[ True  True  True  True  True False  True  True  True  True]

## Task 3: Working with Pandas Series

### Part A: Create and Explore Series
Select a column from your DataFrame (created in Task 1) and work with it as a **Pandas Series**:
1. Extract a Series using `df[column_name]`
2. Print the Series name
3. Print the Series index
4. Print the first 15 values

### Part B: Series Calculations
Using Pandas Series methods (**not** NumPy), calculate:
1. **Value counts** for a categorical column
2. **Basic statistics** for a numeric column
3. **Top N values** (use `.nlargest(5)` or `.nsmallest(5)`)

In [23]:
# Task 3A: Create and explore Series

# YOUR CODE HERE
series1 = df[COL_NUMERIC_1] #average_rating
series2 = df[COL_CATEGORICAL]
# Print name, index, and first 15 values
# YOUR CODE HERE
display(series2.name)
display(series2.index)
display(series2[:15])

'title'

RangeIndex(start=0, stop=11123, step=1)

0     Harry Potter and the Half-Blood Prince (Harry ...
1     Harry Potter and the Order of the Phoenix (Har...
2     Harry Potter and the Chamber of Secrets (Harry...
3     Harry Potter and the Prisoner of Azkaban (Harr...
4     Harry Potter Boxed Set  Books 1-5 (Harry Potte...
5     Unauthorized Harry Potter Book Seven News: "Ha...
6          Harry Potter Collection (Harry Potter  #1-6)
7     The Ultimate Hitchhiker's Guide: Five Complete...
8     The Ultimate Hitchhiker's Guide to the Galaxy ...
9     The Hitchhiker's Guide to the Galaxy (Hitchhik...
10    The Hitchhiker's Guide to the Galaxy (Hitchhik...
11    The Ultimate Hitchhiker's Guide (Hitchhiker's ...
12                 A Short History of Nearly Everything
13                          Bill Bryson's African Diary
14    Bryson's Dictionary of Troublesome Words: A Wr...
Name: title, dtype: str

In [27]:
# Task 3B: Series calculations

# Value counts for categorical column
# YOUR CODE HERE
display(series2.count)
# Statistics for numeric column
# YOUR CODE HERE
display(series1.describe())
# Top N values
# YOUR CODE HERE
display(series1.nlargest(5))

<bound method Series.count of 0        Harry Potter and the Half-Blood Prince (Harry ...
1        Harry Potter and the Order of the Phoenix (Har...
2        Harry Potter and the Chamber of Secrets (Harry...
3        Harry Potter and the Prisoner of Azkaban (Harr...
4        Harry Potter Boxed Set  Books 1-5 (Harry Potte...
                               ...
11118     Expelled from Eden: A William T. Vollmann Reader
11119                          You Bright and Risen Angels
11120                      The Ice-Shirt (Seven Dreams #1)
11121                                          Poor People
11122                          Las aventuras de Tom Sawyer
Name: title, Length: 11123, dtype: str>

count    11123.000000
mean         3.934075
std          0.350485
min          0.000000
25%          3.770000
50%          3.960000
75%          4.140000
max          5.000000
Name: average_rating, dtype: float64

624     5.0
786     5.0
855     5.0
1243    5.0
4125    5.0
Name: average_rating, dtype: float64

## Task 4: DataFrame Indexing and Filtering

### Part A: Filter Data
Create at least THREE filtered DataFrames based on conditions:
1. **Numeric filter**: Select rows where a numeric column meets a condition
   - Example: `df[df['value'] > 100]`
2. **Categorical filter**: Select rows where a categorical column equals something
   - Example: `df[df['category'] == 'TypeA']`
3. **Combined filter**: Use multiple conditions with `&` (and) or `|` (or)
   - Example: `df[(df['value'] > 100) & (df['year'] == 2020)]`. Note the parentheses surrounding each condition! Also, note that Pandas takes the *bitwise* logical operators: `&` for "and"; `|` for "or". This is different from the `and` and `or` conditionals we've seen before.

For each filter:
- Print how many rows remain
- Display the first 5 rows of the filtered DataFrame

### Part B: Column Selection
Select subsets of columns:
1. Select 2-3 columns using a list: `df[['col1', 'col2']]`
2. Use `.loc[]` to select specific rows AND columns
   - Example: `df.loc[0:10, ['col1', 'col2']]`
3. Use `.iloc[]` for position-based selection
   - Example: `df.iloc[0:10, 0:3]`

Print the shape of each selection.

In [49]:
# Task 4A: Filter data

# Filter 1: Numeric condition
# YOUR CODE HERE
# filter average ratings that are greater or equal to 4.5
filtered1 = df[df[COL_NUMERIC_1] >= 4.5]
print(f"Rows after filter 1: {len(filtered1)}")
# display first 5 rows
display(filtered1[:5])
# Filter 2: Categorical condition
# YOUR CODE HERE
filtered2 = df[df[COL_CATEGORICAL].str.contains("Harry")]
print(f"Rows after filter 2: {len(filtered2)}")

# Filter 3: Combined conditions
# YOUR CODE HERE
filtered3 = df[df[COL_NUMERIC_1] == 5 & df[COL_CATEGORICAL].str.contains("Harry")]
print(f"Rows after filter 3: {len(filtered3)}")

Rows after filter 1: 230

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic
6,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,28242,808,9/12/2005,Scholastic
21,30,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,J.R.R. Tolkien,4.59,0345538374,9780345538376,eng,1728,101233,1550,9/25/2012,Ballantine Books

Rows after filter 2: 43
Rows after filter 3: 25

In [56]:
# Task 4B: Column selection

# Select subset of columns
# YOUR CODE HERE
# selecting the title and average_ratings
display(df[[COL_CATEGORICAL,COL_NUMERIC_1]])

# Use .loc[] for row and column selection
# YOUR CODE HERE
display(df.loc[:5,[COL_CATEGORICAL, COL_NUMERIC_1]])
# Use .iloc[] for position-based selection
# YOUR CODE HERE
display(df.iloc[0:3, 0:3])

                                                   title  average_rating
0      Harry Potter and the Half-Blood Prince (Harry ...            4.57
1      Harry Potter and the Order of the Phoenix (Har...            4.49
2      Harry Potter and the Chamber of Secrets (Harry...            4.42
3      Harry Potter and the Prisoner of Azkaban (Harr...            4.56
4      Harry Potter Boxed Set  Books 1-5 (Harry Potte...            4.78
...                                                  ...             ...
11118   Expelled from Eden: A William T. Vollmann Reader            4.06
11119                        You Bright and Risen Angels            4.08
11120                    The Ice-Shirt (Seven Dreams #1)            3.96
11121                                        Poor People            3.72
11122                        Las aventuras de Tom Sawyer            3.91

[11123 rows x 2 columns]

                                               title  average_rating
0  Harry Potter and the Half-Blood Prince (Harry ...            4.57
1  Harry Potter and the Order of the Phoenix (Har...            4.49
2  Harry Potter and the Chamber of Secrets (Harry...            4.42
3  Harry Potter and the Prisoner of Azkaban (Harr...            4.56
4  Harry Potter Boxed Set  Books 1-5 (Harry Potte...            4.78
5  Unauthorized Harry Potter Book Seven News: "Ha...            3.74

,bookID,title,authors
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling

## Task 5: Building Reusable Functions and Creating Summaries

Now that you've explored individual operations, let's put it all together by writing a **reusable function** and creating a summary of your analysis.

### Part A: Write a Reusable Analysis Function
Create a function `analyze_column(df, column_name, column_type)` that:
1. Takes a DataFrame, column name, and column type (`'numeric'` or `'categorical'`) as parameters
2. Returns a **dictionary** containing appropriate statistics based on the column type:
   - **For numeric columns:** count, mean, median, std, min, max, missing values
   - **For categorical columns:** count, unique values, top 3 most common values with counts, missing values

**Function signature:**
```python
def analyze_column(df, column_name, column_type):
    """
    Analyze a column and return appropriate statistics.
    
    Parameters:
        df (pd.DataFrame): The DataFrame containing the data
        column_name (str): Name of the column to analyze
        column_type (str): Either 'numeric' or 'categorical'
        
    Returns:
        dict: Dictionary containing analysis results
    """
    return analysis_dict
```

*(The signature above is just for reference, write your code in the code cell below, which already contains this skeleton.)*

**After defining the function:**
- Call it on 2-3 columns from your dataset (mix of numeric and categorical)
- Print the results in a readable format

### Part B: Create and Save a Summary DataFrame
Using the function you wrote in Part A or techniques from earlier tasks:
1. Create a **new DataFrame** that summarizes your data in a meaningful way. For example, you could make a summary of statistics by category or a comparison of means across different filters.
   - You could combine results from multiple calls to your `analyze_column()` function
   - Or create a comparison of different filtered subsets
2. Make sure your summary DataFrame has:
   - Appropriate column names
   - Clear, interpretable values
   - At least 3 rows and 3 columns
3. Save it to a CSV file: `a3_summary.csv`
   - Tip: the starter code saves with `index=False`. If your summary's most important labels live in the **index** (for example, after a `groupby()`), call `.reset_index()` first, or save with `index=True`, so those labels aren't lost.

In [12]:
# Task 5A: Write reusable analysis function


def analyze_column(df, column_name, column_type):
    """
    Analyze a column and return appropriate statistics.

    Parameters:
        df (pd.DataFrame): The DataFrame containing the data
        column_name (str): Name of the column to analyze
        column_type (str): Either 'numeric' or 'categorical'

    Returns:
        dict: Dictionary containing analysis results
    """
    analysis_dict = {"column": column_name, "type": column_type}

    if column_type == "numeric":

        # YOUR CODE HERE
        ...

    elif column_type == "categorical":

        # YOUR CODE HERE
        ...

    return analysis_dict


# Test the function on 2-3 columns
# YOUR CODE HERE
# result1 = analyze_column(df, COL_NUMERIC_1, 'numeric')
# print(f"\nAnalysis for {COL_NUMERIC_1}:")
# for key, value in result1.items():
#     print(f"  {key}: {value}")

# result2 = analyze_column(df, COL_CATEGORICAL, 'categorical')
# print(f"\nAnalysis for {COL_CATEGORICAL}:")
# for key, value in result2.items():
#     print(f"  {key}: {value}")

In [13]:
# Task 5B: Create and save summary DataFrame

summary_df = ... # Change the ellipsis (...) to the actual construction of the summary DataFrame
# YOUR CODE HERE

print("\nSummary DataFrame:")
display(summary_df)

# Save to CSV
# (If your summary's labels are in the index — e.g., after groupby() —
#  use summary_df.reset_index() first, or set index=True below.)
summary_df.to_csv("a3_summary.csv", index=False)
print("Summary saved to a3_summary.csv")

Summary DataFrame:

Ellipsis

AttributeError: 'ellipsis' object has no attribute 'to_csv'

---

## Submission Checklist
- [ ] **Task 1:** Data loaded with pd.read_csv(); DataFrame explored (shape, dtypes, describe, info, missing values).
- [ ] **Task 2:** Columns converted to NumPy arrays; array statistics calculated; at least 2 array operations performed.
- [ ] **Task 3:** Series created and explored (name, index); Series calculations performed (value_counts, statistics).
- [ ] **Task 4:** 3+ filters applied to DataFrame (numeric, categorical, and combined conditions); column selections demonstrated with lists, .loc[], and .iloc[].
- [ ] **Task 5:** Reusable `analyze_column()` function written and tested on multiple columns; summary DataFrame created and saved to CSV.
- [ ] All code cells run without errors.
- [ ] Code is well-commented and explains what each operation does.
- [ ] Output is clearly labeled and easy to understand.
- [ ] NumPy and Pandas used appropriately.

### Grading Rubric
- **Task 1: Data Loading and Exploration (20%):** Successfully loads data and correctly uses Pandas methods to explore the DataFrame (shape, dtypes, describe, info, missing values).
- **Task 2: NumPy Array Operations (20%):** Correctly converts to arrays, calculates statistics with NumPy functions, performs meaningful array operations.
- **Task 3: Pandas Series (20%):** Properly works with Series and uses Series methods correctly.
- **Task 4: DataFrame Indexing and Filtering (20%):** Applies multiple filters correctly and uses .loc[] and .iloc[] appropriately.
- **Task 5: Reusable Function and Summary (20%):** Writes correct, reusable function with proper parameters and return values; tests function on multiple column types; creates meaningful summary DataFrame and saves to CSV; explains approach clearly.

**Total: 100 points**

### Academic Integrity
Work individually. You may discuss general approaches with classmates, but all code, analysis, and writing must be your own. Cite any external resources used beyond course materials and official documentation.

### Submission Instructions
Submit via Moodle:
1. This completed Jupyter notebook (`.ipynb` file)
2. Your summary data (`a3_summary.csv`)
3. Your original dataset file (if you're using something other than the datasets provided on Moodle)